### ISSUE TITLE
Issues and config not loading for a repo

### ISSUE THREAD

**Issue by spengrah** [wslyvh/tokenlog#15]
I tried setting up tokenlog for another repo and the UI is not loading any of the issues (just the spinner) - https://tokenlog.xyz/raid-guild/RIPs

**Comment by wslyvh** [comment]
There was a comma after the last prop at your config, which made it unable to parse the settings.
I've created a PR on your repo: https://github.com/raid-guild/RIPs/pull/31
It should work if you merge the PR/update the config.

I see that was in the readme/doc as well, so updated the documentation again. 
Let me know how it goes, so I can close this issue.

**Comment by spengrah** [comment]
OK great - thanks! It's working now :)

**Comment by wslyvh** [comment]
Cool. Glad to hear!
