### ISSUE TITLE
Creating duel tokens in token log and needing contribution/ React and Typescript

### ISSUE THREAD

**Issue by freedumbs00** [wslyvh/tokenlog#17]
https://github.com/TECommons/coordination/issues/311.   

Forwarding as requested.   Thank you so much for the update.

**Comment by wslyvh** [comment]
Tracking the work at PR #16

**Comment by freedumbs00** [comment]
https://deploy-preview-16--tokenlog.netlify.app/TECommons/coordination.   I also deployed the Impact hour tokens.  Fantastic job Wes!
