### ISSUE TITLE
Support for voting using ERC721 tokens

### ISSUE THREAD

**Issue by adrianleb** [wslyvh/tokenlog#19]
Hey all, 
At @ethblockart, we're looking at using tokenlog for a public-facing product backlog, assigning voting power to NFTs minted by participants in the system rather than implementing a governance token.
 
Given our plans to have 3 different NFT primitives with different properties and utilities, we think this could be a great opportunity to experiment with a few variations of this model and an initiative that we can approach as a rolling collaboration.

Today we have 2 of the 3 primitives deployed to mainnet. When thinking about voting power, this comes to mind at a high level:

**BlockArts** are the core primitive NFTs in the system, created by any participant, using BlockStyle NFTs as a template.* these could be a good fit for a 1-token, 1-vote like model. It is likely for participants to one more than one BlockArt.*

**BlockStyles** are scarce NFTs, created and initially owned by creative coders and used within the platform to seed the creation of N BlockArts.* these could be good for a 1-token, n-votes model, giving a louder voice to system participants who have the system's success and health aligned with their own incentives.*

I would love to hear what others think of this idea and how we could approach this exploration!

These are the addresses of both tokens:

BlockArt NFTs: 0xb80fbf6cdb49c33dc6ae4ca11af8ac47b0b4c0f3
BlockStyle NFTs: 0x73c8460f8043a4521c889a3cc23d1c81214a1d25

Thank you!

**Comment by wslyvh** [comment]
Hi, thanks for submitting this Adrian! 
It's definitely interesting to implement ERC721 as a new way of voting. 

I think your idea of giving different voting power per NFT makes sense.
So BlockArts represents 1 vote, while BlockStyles are more scarce and could potentially having more voting power.
Happy to explore and see how we can implement different strategies.

I can imagine both NFT-holders will still vote on the same issues (same repo), right?
That would mean a single repo, should support multiple tokens? I'm implementing something similar for TEC #17

**Comment by wslyvh** [comment]
Standard 1-NFT, 1-vote completed.
Example repo at https://tokenlog.xyz/ethblockart/backlog 

Happy to talk about other mechanisms and strategies, but closing this issue for now.
