### ISSUE TITLE
Implement quadratic voting

### ISSUE THREAD

**Issue by wslyvh** [wslyvh/tokenlog#2]
As a repo owner, I want to configure my repository to allow for quadratic voting, instead of 1 token 1 vote. 

Quadratic voting formula: Cost to the voter = (Number of votes)^2

**Comment by wslyvh** [comment]
Completed

**Comment by spengrah** [comment]
How can QV be configured for a given repo?

**Comment by wslyvh** [comment]
Hi @slgraham

You can add the following param to your tokenlog.json
`"votingMethod": "QUADRATIC"`
(default is STANDARD)

I've updated the documentation on the readme with an example configuration. Let me know if you need anything!

**Comment by spengrah** [comment]
Thanks @wslyvh! The QV works great.

One semi-related question (couldn't find a better place to ask it): when, if ever, does the vote power reset? In other words, once I've "spent" all my tokens on votes, when can I vote again?

**Comment by wslyvh** [comment]
Good question. Again, this wasn't documented before, so updated the readme :) 

Once voted on an issue, these votes will remain 'fixed' until the issue is resolved. When an issue is closed, all votes on it will be 'released' and available to use for voting on other issues. Would that work for you, or do you think other mechanisms would work better (e.g. unvote, or use voting periods)?

**Comment by spengrah** [comment]
I think that approach makes the most sense. As a voter, my goal is to influence the product team's assessment, so once that assessment has been made either way (i.e. the issue is closed) I would want my votes released.

There may be a bug in the vote release - in https://tokenlog.xyz/HausDAO/pokemol-web , I have a total of 150 tokens and have voted with 39 of them. I should have 111 available, but the app only shows 96 available. I did "spend" 15 tokens on an issue that is now closed, but those should now be available to me. I suspect this is because I switched the config to QV before closing the first issue.

The ability to unvote would also be nice, though I suppose that could introduce some ability for spamming (e.g. repeated voting and unvoting to add noise to the signal). There are definitely times when changing one's mind is legitimate, though.

**Comment by wslyvh** [comment]
Got it. No unvotes were intentional at least for this first release. To avoid spamming, or constantly changing votes (re-prioritizing) while the team might already be working on it. I can definitely imagine there are indeed cases where unvoting/changing your mind can be legitimate. But I'd like to get more feedback on it first. So happy to discuss further if you have such cases.

RE Vote release, I haven't tested to switch voting mechanisms when votes are cast already. I guess it should work, except that some votes would have a wrong cost associated with it.
What's more likely is that the background job didn't run yet. This is currently a daily job, in order to have some sort of 'cool-off' period in case an issue gets closed by accident (or on purpose to release votes) and re-opened shortly after. This could probably get lowered to a few hours? 

I just ran the job manually. Please have a look if you're tokens are released now? Otherwise, I'd be happy to further debug this.

**Comment by spengrah** [comment]
> Got it. No unvotes were intentional at least for this first release. To avoid spamming, or constantly changing votes (re-prioritizing) while the team might already be working on it. I can definitely imagine there are indeed cases where unvoting/changing your mind can be legitimate. But I'd like to get more feedback on it first. So happy to discuss further if you have such cases.

Agreed, that makes sense. If any unvote cases come up for us I'll let you know.

> Please have a look if you're tokens are released now? Otherwise, I'd be happy to further debug this.

Doesn't look like my votes were released. I'm still seeing 96 available. 

Also, I've noticed that occasionally the token name/available vote info doesn't get displayed, and instead a message like "this repo isn't configured yet" is displayed. Its intermittent, and I haven't been able to tell what might triggering it. So just FYI.

**Comment by wslyvh** [comment]
Hm, I'd have to debug it more to find out how votes are allocated then. Is it just you who voted on that repo (HausDAO/pokemol-web)? Or are there others. Or could you send me your address (telegram/discord is fine)?
I can imagine it has to do with the switch from standard to QV.

RE not values not getting displayed sometimes. Do you know if that is after taking any action (e.g. voting)? And/or are you logged in? There are definitely a few performance improvements to be made and I did notice that it sometimes takes a while until state changes are properly updated. That might be it?

**Comment by wslyvh** [comment]
But thanks for all the feedback btw. This is all very helpful!

**Comment by spengrah** [comment]
>  Is it just you who voted on that repo (HausDAO/pokemol-web)? Or are there others.
There are a few others who have voted. I'm the only one who voted before I changed the config to QV. Just sent you my address on telegram

> RE not values not getting displayed sometimes. Do you know if that is after taking any action (e.g. voting)? And/or are you logged in? 
Not that I can tell. I just voted to check, and no change. I'm definitely logged in with the correct address and pointed to the correct network. Currently I am not seeing the values, though I've definitely seen them before for this repo/token.

**Comment by wslyvh** [comment]
There was a bug in the background job that should close the votes. Apparently, it didn't. 
Votes on closed issues should be released again now. 
And it's running every 6 hours now, instead of daily. `

I also noticed the other issues you mentioned of getting intermittent 'Repo is not configured' messages. 
Created a new issue #18 to track
