### ISSUE TITLE
Remove Voting Points from the 2 token view

### ISSUE THREAD

**Issue by GriffGreen** [wslyvh/tokenlog#22]
Ok I did find an issue!

Its a bonus...nice to have... not a blocker

<img width="384" alt="Screen Shot 2021-02-03 at 4 27 57 PM" src="https://user-images.githubusercontent.com/14945613/106812688-4ed6c380-6670-11eb-814e-4f9b153c5b8e.png">

It would be AMAZING if we could show the 2 token balances and the % of voting power (the normalized VP) and hide the VP number from the user since they don't know/ don't care what it is.

This would be nice so that the user can notice if there is an error in their token balance... that they expected to have a different number of CSTK or IH

**Comment by wslyvh** [comment]
This makes sense. Updated!

![image](https://user-images.githubusercontent.com/25974464/114172893-94489300-9936-11eb-8639-17dd9ed04248.png)
