### ISSUE TITLE
Template chooser bypassed when creating new issues

### ISSUE THREAD

**Issue by kristoferlund** [wslyvh/tokenlog#26]
# Observed behaviour

When creating a new issue from the TokenLog interface, the user is directed to https://github.com/[repo]/issues/new.

But.. If the repository has issue templates activated that means bypassing the step where the user gets to choose template. This is the case with the [TEC TokenLog SoftGov](https://github.com/TECommons/TokenLog-SoftGov) for instance.

# Proposed solution

TokenLog checks if the repo has issues enabled and redirects the user to the issue template chooser instead.

Template chooser: https://github.com/[repo]/issues/new/choose

**Comment by kristoferlund** [comment]
@wslyvh

Could adding an item to the `RepositorySettings` be an option?

```
useIssueTemplates: true|false (default false)
```

**Comment by wslyvh** [comment]
Fixed! Great suggestion, thanks!

It's added by default. Apparently, Github handles a redirect itself if there are no templates.
