### ISSUE TITLE
Make it easier to open the issue for viewing

### ISSUE THREAD

**Issue by GriffGreen** [wslyvh/tokenlog#29]
One good option would be to make the title a hyperlink... but the small # on the right isn't making me want to click it... Maybe also that could be a larger font?

<img width="127" alt="Screen Shot 2021-04-20 at 11 46 15 AM" src="https://user-images.githubusercontent.com/14945613/115448158-aae5c880-a219-11eb-91e2-960e8c48488a.png">

Or maybe the whole box could be a hyperlink for the issue besides the vote spot

**Comment by wslyvh** [comment]
The idea for making it small(er), was that people should be able to make informed decisions and vote, based on the information (title, #, metadata, etc.). For Commons, it's clear you have much more information behind each item. 
What information would be necessary to pull into Tokenlog to be able to make a decision, without the need to switch between systems? Just the body of each item? Maybe in a collapsible panel?

**Comment by liviade1** [comment]
A collapsible panel with all the info sounds perfect! if all the body of text was accessible without having to open another page it would be great.

**Comment by wslyvh** [comment]
@robertovalenti was kind enough to submit a PR for clickable titles 🙌

Will close the issue and think about collapsible panels for another release.
