### ISSUE TITLE
Adding new sites

### ISSUE THREAD

**Issue by robertovalenti** [wslyvh/tokenlog#39]
Am I the only one experiencing voting issues on new repos? There seems to be a  database connection problem with the netlify functions, I have never used them so I am not sure how to debug it.

To recreate:
go to tokenlog.xyz/liminalvillage/governance
vote with DAI

Error:
Unable to cast vote. Please check your account and available voting power.
in the console: 

In the console:
POST https://tokenlog.xyz/.netlify/functions/vote?org=liminalvillage&repo=governance 502
(anonymous) @ xhr.js:184
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
r.forEach.u.<computed> @ Axios.js:86
(anonymous) @ bind.js:9
(anonymous) @ VotingService.ts:185
f @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
g @ 6.27f3e988.chunk.js:1
CreateVote @ 6.27f3e988.chunk.js:1
(anonymous) @ VotingCard.tsx:75
f @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
n @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
H @ VotingCard.tsx:16
(anonymous) @ VotingCard.tsx:16
onClick @ VotingCard.tsx:176
s @ react-dom.production.min.js:14
d @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
at @ react-dom.production.min.js:52
it @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
dt @ react-dom.production.min.js:56
U @ react-dom.production.min.js:287
z @ react-dom.production.min.js:19
Xt @ react-dom.production.min.js:70
$t @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Hi @ react-dom.production.min.js:122
D @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
VotingService.ts:190 Couldn't POST vote

**Comment by wslyvh** [comment]
Seems like you've copied/forked the configuration from this repo. 
This is using a different format in preparation for the latest development/release. 
That's not public yet and won't work for any other repos.

I've submitted a PR on your repo with a correct tokenlog.json.
Or check out the readme/docs if you want to configure any other. 

Closing this issue.
