### ISSUE TITLE
Bug: does not show how many votes remain (says NaN)

### ISSUE THREAD

**Issue by tamarandom** [wslyvh/tokenlog#43]
![image_2021-06-01_09-55-23](https://user-images.githubusercontent.com/703624/120287897-f632d280-c2bf-11eb-9f1f-612b72bd309e.png)

**Comment by tamarandom** [comment]
I was on rinkeby not xdai. It works fine on xdai!

**Comment by wslyvh** [comment]
Ah. Great to hear! Thanks for following up :)
