### ISSUE TITLE
A couple Commons Stack related edits :)

### ISSUE THREAD

**Issue by krisjpi** [wslyvh/tokenlog#44]
A couple small requested changes:
- change the logo on the Token Engineering Commons repo from the tokenlog homepage (currently Commons Stack Logo)
- change the link from the Commons Stack logo from the tokenlog homepage to the Commons Stack iteration 0 repo (currently links to a TEC SoftGov page)

Thanks for all your work!

**Comment by wslyvh** [comment]
Hi @krisjpi, thanks for the requests. Updated! 

We're getting close to releasing a new version. 
This will automatically update the homepage with repositories that are configured & have votes. No need to manually updated anymore :)
