### ISSUE TITLE
User Interface Design Improvement

### ISSUE THREAD

**Issue by mnvvr** [wslyvh/tokenlog#45]
Hello,

I stumbled upon TokenLog recently and I loved it. But the user interace definitely could be improved. Readme says contributions are welcome. I would be happy to contribute this project by designing a new user interface. As soon as you approve, I can start working on this. 

#### About me
I'm a product designer, designing digital products most recently. 
My portfolio: https://munevver.dribbble.com/

Best,
Münevver

**Comment by wslyvh** [comment]
Hi, thanks for reaching out 🙏

I'm going to close this one and continue discussion on #10
