### ISSUE TITLE
Feature Request: Downvotes

### ISSUE THREAD

**Issue by 0xferit** [wslyvh/tokenlog#47]
It would be nice to be able to cast downvotes. Like upvotes, it should use voting credits. For example, in a quadratic voting setting, casting downvotes 5 times would spend 25 voting credits.

**Comment by 0xferit** [comment]
Noticed #46 now.

**Comment by wslyvh** [comment]
Yes, duplicate issue at #46 

I'll definitely keep it at the backlog, but will close this issue. Thanks!
