### ISSUE TITLE
Repos not loading

### ISSUE THREAD

**Issue by nya-elimu** [wslyvh/tokenlog#61]
https://tokenlog.xyz/elimu-ai/wiki

<img width="404" src="https://user-images.githubusercontent.com/15718174/208360643-a2f1a40c-806a-4313-8c7d-af753bb7cb4a.png">

Is tokenlog.xyz no longer being maintained?

**Comment by wslyvh** [comment]
Tokenlog.xyz is running the initial/MVP version.

The latest release can be found here
https://github.com/GeneralMagicio/tokenlog

**Comment by nya-elimu** [comment]
> Tokenlog.xyz is running the initial/MVP version.
> 
> The latest release can be found here https://github.com/GeneralMagicio/tokenlog

Thanks, @wslyvh, got it working: https://tokenlog.generalmagic.io/elimu-ai/web3-wiki
